// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MvyAEhjUaITpkjbT3J2FJVt9qdFjkaE',
    appId: '1:25337554903:web:7c3d3e87bd6b8e7f038d92',
    messagingSenderId: '25337554903',
    projectId: 'chatii-46e28',
    authDomain: 'chatii-46e28.firebaseapp.com',
    storageBucket: 'chatii-46e28.appspot.com',
    measurementId: 'G-G66TYYNHM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1zk3BuFqIGlgC3UFFKefRkGDClhJKf0',
    appId: '1:25337554903:android:dcaeaf5ba37aec68038d92',
    messagingSenderId: '25337554903',
    projectId: 'chatii-46e28',
    storageBucket: 'chatii-46e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWXJOqbYs6ZZadxO-TJR3ZoWVouhMf0I',
    appId: '1:25337554903:ios:1783482d96be2204038d92',
    messagingSenderId: '25337554903',
    projectId: 'chatii-46e28',
    storageBucket: 'chatii-46e28.appspot.com',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCWXJOqbYs6ZZadxO-TJR3ZoWVouhMf0I',
    appId: '1:25337554903:ios:1783482d96be2204038d92',
    messagingSenderId: '25337554903',
    projectId: 'chatii-46e28',
    storageBucket: 'chatii-46e28.appspot.com',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3MvyAEhjUaITpkjbT3J2FJVt9qdFjkaE',
    appId: '1:25337554903:web:3ff43544fa263318038d92',
    messagingSenderId: '25337554903',
    projectId: 'chatii-46e28',
    authDomain: 'chatii-46e28.firebaseapp.com',
    storageBucket: 'chatii-46e28.appspot.com',
    measurementId: 'G-6EZ6ZN771H',
  );
}
